name: Build and Deploy Hugo Site to `public` Branch

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: write  # Needed to push to another branch

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Install Node.js dependencies (if present)
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          fi

      - name: Build Hugo site
        env:
          HUGO_ENVIRONMENT: production
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
        run: |
          hugo --minify

      - name: Push `public/` folder to `public` branch
        run: |
          cd public
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b public
          git add .
          git commit -m "Deploy Hugo site: $(date)"
          git push --force origin public 

